from .academicYear import AcademicYear
from .course import Course
from .lecture import Lecture
from .lectureResources import LectureResource
from .school import School
from .standard import Standard
from .student import Student
from .subject import Subject
from .teacher import Teacher
