from .course import Course  # noqa: F401
from .discussion import Discussion  # noqa: F401
from .institution import Institution  # noqa: F401
from .lecture import Lecture  # noqa: F401
from .notifications import Notifications  # noqa: F401
from .registration import Registration  # noqa: F401
from .resource import Resource  # noqa: F401
from .standard import Standard  # noqa: F401
from .user import User  # noqa: F401
